name: Install dependencies
description: 'Installs and caches the dependencies'

runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      shell: bash
      run: yarn install --frozen-lockfile

    - name: Cache
      uses: actions/cache@v3
      with:
        path: ./node_modules
        key: ${{ hashFiles('./package.json') }}

    - name: Cache example node modules
      id: cache-example-npm
      uses: actions/cache@v3
      env:
        cache-name: cached-example-npm-deps
      with:
        path: example/node_modules
        key: ${{ hashFiles('./example/yarn.lock') }}-${{ hashFiles('./yarn.lock') }}

    - name: Install required example dependencies on yarn.lock change
      if: steps.cache-example-npm.outputs.cache-hit != 'true'
      shell: bash
      run: yarn install --frozen-lockfile
      working-directory: example
