name: Install dependencies
description: 'Installs and caches the dependencies'

runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      shell: bash
      run: bun install

    - name: Cache
      uses: actions/cache@v3
      with:
        path: ./node_modules
        key: ${{ hashFiles('./package.json') }}

    - name: Cache example node modules
      id: cache-example-npm
      uses: actions/cache@v3
      env:
        cache-name: cached-example-npm-deps
      with:
        path: example/node_modules
        key: ${{ hashFiles('./example/bun.lockb') }}-${{ hashFiles('./bun.lockb') }}

    - name: Install required example dependencies on bun.lockb change
      if: steps.cache-example-npm.outputs.cache-hit != 'true'
      shell: bash
      run: bun install
      working-directory: example