require_relative '../../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative 'RNPod'

platform :ios, '10.0'

target 'ViewPagerExample' do

  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  pod 'react-native-viewpager', :path => '../../react-native-viewpager.podspec'

  target 'ViewPagerExampleTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end

end

target 'ViewPagerExample-tvOS' do
  # Pods for ViewPagerExample-tvOS

  target 'ViewPagerExample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
