name: iOS Build

on:
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/ios.yml'
      - 'ios/**'
      - 'example/ios/**'
  push:
    branches:
      - master


jobs:
  ios-build:
    runs-on: macos-14
    concurrency:
      group: ${{ github.ref }}-ios
      cancel-in-progress: true
    steps:
      - uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install dependencies
        shell: bash
        run: bun install

      - name: Install example dependencies
        shell: bash
        run: bun install
        working-directory: example

      - name: Cache Pods
        id: cache-pods
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        env:
          cache-name: cached-ios-pods-deps
        with:
          path: example/ios/Pods
          key: ${{ hashFiles('./example/ios/Podfile.lock') }}

      - name: Bundle app
        run: bun build:ios
        working-directory: example

      - name: Install example Pods
        run: bun pods
        working-directory: example

      - name: Install Maestro CLI
        run: |
          export MAESTRO_VERSION=1.31.0; curl -Ls "https://get.maestro.mobile.dev" | bash
          brew tap facebook/fb
          brew install facebook/fb/idb-companion

      - name: Add Maestro to path
        run: echo "${HOME}/.maestro/bin" >> $GITHUB_PATH

      - name: Build iOS App
        run: |
          bun example:ios:release

      - name: Run tests
        run: |
          bun test:e2e:ios
